services:
  app:
    build: .
    ports:
      - "3321:3321"
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=urchin_article
      - MYSQL_USER=rootie
      - MYSQL_PASSWORD=1121
    depends_on:
      - redis
      - mysql

  redis:
    image: redis
    restart: always

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: roott
      MYSQL_DATABASE: urchin_article
      MYSQL_USER: rootie
      MYSQL_PASSWORD: 1121
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app